import {Task, TaskStatus, TaskPriority, TaskCategory} from '../../models/Task';

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Complete Project Proposal',
    description: 'Write and submit the Q2 project proposal',
    status: TaskStatus.TODO,
    priority: TaskPriority.NORTH_STAR,
    category: TaskCategory.TODAY,
    timeEstimate: 120,
    subtasks: [
      {
        id: '1-1',
        parentId: '1',
        title: 'Research market trends',
        status: TaskStatus.COMPLETED,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '1-2',
        parentId: '1',
        title: 'Draft executive summary',
        status: TaskStatus.TODO,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
      {
        id: '1-3',
        parentId: '1',
        title: 'Create budget estimates',
        status: TaskStatus.TODO,
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
      },
    ],
    notes: 'Focus on ROI and scalability aspects',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '2',
    title: 'Review Team Updates',
    status: TaskStatus.TODO,
    priority: TaskPriority.MEDIUM,
    category: TaskCategory.TODAY,
    timeEstimate: 30,
    subtasks: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: '3',
    title: 'Plan Sprint Goals',
    status: TaskStatus.TODO,
    priority: TaskPriority.HIGH,
    category: TaskCategory.NEXT,
    timeEstimate: 60,
    subtasks: [],
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];
